### ISSUE TITLE
Selecionar Instalação do Mapas

### ISSUE THREAD

**Issue by GustavoVS** [hacklabr/mapasculturais-app#10]
No menu de configurações, ao selecionar uma instalação:
- O mapa não centraliza na lat, long e zoom corretos.
- Os dados da instalação (ou instalações) anterior continua no mapa.

Ao fechar e abrir o aplicativo novamente, os dados são carregados corretamente.

**Comment by thaisrigolon** [comment]
Incompatibilidade com o Android 6.x. Os dados no mapa não carregam, mesmo ao tentar alterar a Instalação do Mapas Culturais.
