### ISSUE TITLE
Inserir rodapé no app

### ISSUE THREAD

**Issue by thaisrigolon** [hacklabr/mapasculturais-app#12]
Produzido por [Instituto TIM](http://institutotim.org.br/) e [MinC](http://www.cultura.gov.br/)

**Comment by marcospf-eng** [comment]
Olá @thaisrigolon ! Sei que a issue é antiga, mas gostaria de saber se vocês tem interesse ainda nessa feature. Se sim, como posso ajudá-los?

**Comment by thaisrigolon** [comment]
Olá, @marcospf-eng obrigada! No entanto, não é necessário. Já adicionamos as marcas do Instituto TIM e do MinC na abertura do app. Obrigada mesmo.
