### ISSUE TITLE
Logo do Instituto TIM no Sobre

### ISSUE THREAD

**Issue by thaisrigolon** [hacklabr/mapasculturais-app#14]
O Logo do Instituto TIM não está visível no "Sobre" do app, conforme evidência: 
![erro](https://cloud.githubusercontent.com/assets/18294515/16564306/21f4c6e4-41dd-11e6-8300-04b1ffe96fc4.png)

**Comment by lfagundes** [comment]
Já foi feito, vai sair no próximo build. Aparentemente há versões novas das bibliotecas e não estou conseguindo fazer o plugin de Mapa funcionar no Android.
