### ISSUE TITLE
Incompatibilidade Android 6.0

### ISSUE THREAD

**Issue by GustavoVS** [hacklabr/mapasculturais-app#16]
As informações não são carregadas quando executado na versão 6.0 do Android, versão usada por quase 1/5 dos usuários (https://developer.android.com/about/dashboards/index.html#Platform).

Após alteração efetuada na issue #10.

**Comment by brunosmartin** [comment]
Executei no Android 6.0.1 e abriu normalmente, tanto o mapa quanto as demais telas.
Vocês poderiar fornecer mais detalhes?
Para testar este apk de teste usando o arquivo enviado é importante desinstalar o aplicativo do Mapas Culturais antes, caso ele tenha sido instalado usando a loja do google play.

**Comment by GustavoVS** [comment]
Após limpar os dados do aplicativo nas configurações do sistema, desinstalar e instalar novamente o aplicativo as informações passaram a funcionar.
