### ISSUE TITLE
Inserir versão do aplicativo

### ISSUE THREAD

**Issue by intrepidocabral** [hacklabr/mapasculturais-app#4]
O aplicativo precisa de versionamento, tanto no código quanto no build. O usuário precisa saber qual versão ele tem instalado. Essa informação no build pode ser inserida no SOBRE.

**Comment by brunosmartin** [comment]
O próprio aplicativo tem um controle da versão, que pode ser visto na google play ou na apple store. Sugiro fechar esta aqui.

**Comment by thaisrigolon** [comment]
O número da versão precisa ficar embaixo do texto do "Sobre". No momento está acima do texto.
