### ISSUE TITLE
Atualizar sobre

### ISSUE THREAD

**Issue by intrepidocabral** [hacklabr/mapasculturais-app#9]
- Inserir texto "Sobre"
- Inserir logos: Minc + Instituto TIM

**Comment by thaisrigolon** [comment]
Texto "Sobre":

O aplicativo Mapas Culturais foi desenvolvido pelo Instituto TIM em parceria com o Ministério da Cultura, para divulgar a programação cultural brasileira. Com ele, você acessa informações sobre eventos e espaços culturais de todo o país. O aplicativo é alimentado com os dados do Sistema Nacional de Informações e Indicadores Culturais e de instalações em estados e municípios da plataforma Mapas Culturais – software livre para gestão e mapeamento da cultura desenvolvido pelo Instituto TIM.

Mais informações: [institutotim.org.br](http://institutotim.org.br/) / [sniic.cultura.gov.br](http://sniic.cultura.gov.br/) / [github](https://github.com/institutotim/mapasculturais)

**Comment by thaisrigolon** [comment]
Marca do Instituto TIM.

![logo_instituto_tim_rgb](https://cloud.githubusercontent.com/assets/18294515/16337893/2d114eda-39ef-11e6-86fe-ddfce151c86f.jpg)
![logo_instituto_tim_rgb](https://cloud.githubusercontent.com/assets/18294515/16337894/2d2f0bd2-39ef-11e6-8f24-60cf51a3b46b.png)
[160217_TIM_InstitutoTIM_Guia_Marca_2016_V01_LA.PDF](https://github.com/hacklabr/mapasculturais-app/files/331740/160217_TIM_InstitutoTIM_Guia_Marca_2016_V01_LA.PDF)
